### ISSUE TITLE
Array of Floats - Assert Failure

### ISSUE THREAD

**Issue by hblumberg** [huangyihe/llvm-3.6.0#3] opened 2015-04-15 18:18 UTC
The following assert in LoadRealValueFromMemory fails when dealing with arrays of floats:
assert(result->second->GetExtFloatTy() == FloatTy);

(For example, using float xs[5] = {1000000, 0.01, 0.01, 0.01, 0.01); in our toy example.)

**Comment by huangyihe** [comment] 2015-04-24 17:27
I can't reproduce this problem right now... Can anybody verify that it's somehow fixed already?

**Comment by danking** [comment] 2015-04-24 17:37
Can't reproduce this, WONTFIX

**Closed by danking** 2015-04-24 17:37 UTC
